wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1648106399
    t:
      1:
      - 1
      - 41
      2:
      - 1
      - 41
      3:
      - 1
      - 2
      4: 3.8.5
      5: 0.12.11
      8:
      - 1
      - 3
      - 5
